import type { Problem } from '@rankup/api';
import type { MockHandler } from './types.js';

type NotImplementedProblem = Problem;

export const notImplementedOperationIds = [
	'abortUpload',
	'acceptFriendRequest',
	'acceptMyTournamentInvite',
	'batchUpdateMyNotifications',
	'blockUser',
	'cancelMyFriendRequest',
	'cancelTournamentInvite',
	'changeMyPassword',
	'claimMyReward',
	'completeUpload',
	'confirmPasswordReset',
	'confirmRegistration',
	'createFriendRequest',
	'createMyAppeal',
	'createOauthLink',
	'createReport',
	'createSession',
	'createTournamentInvitationCode',
	'createTournamentInvites',
	'createUpload',
	'declineFriendRequest',
	'declineMyTournamentInvite',
	'deleteMe',
	'deleteMedia',
	'deleteMyDevice',
	'deleteOauthLink',
	'deleteTournamentChatMessage',
	'dismissMyNotification',
	'editTournamentChatMessage',
	'followUser',
	'getAchievementDefinition',
	'getAchievementMeta',
	'getAppBootstrap',
	'getAppConfig',
	'getCompetition',
	'getCompetitionSeason',
	'getCreator',
	'getCreatorCollection',
	'getCreatorHub',
	'getGameMode',
	'getHealthz',
	'getMatch',
	'getMe',
	'getMedia',
	'getMyAchievement',
	'getMyAppeal',
	'getMyEnforcementStatus',
	'getMyFeedItem',
	'getMyFeedReadCursor',
	'getMyFriendRequest',
	'getMyFriendRequestUnreadCount',
	'getMyNotification',
	'getMyNotificationPreferences',
	'getMyNotificationUnreadCount',
	'getMyPreferences',
	'getMyPrivacy',
	'getMyPromotionStatus',
	'getMyRankedProfile',
	'getMyRankedSettings',
	'getMyRankedTrack',
	'getMyRecap',
	'getMyRelationshipWithUser',
	'getMyReport',
	'getMyReward',
	'getMyRewardFulfillmentProfile',
	'getMyStats',
	'getMyTournamentInvite',
	'getMyTournamentInviteUnreadCount',
	'getMyTournamentMatchdayStats',
	'getMyTournamentStats',
	'getPromotion',
	'getRankedLeaderboard',
	'getRankedMeta',
	'getRankedSeason',
	'getRankedSeasonLeaderboard',
	'getRankedTrack',
	'getReadyz',
	'getRuleset',
	'getTeam',
	'getTournamentChat',
	'getTournamentChatMessage',
	'getTournamentChatReadCursor',
	'getTournamentChatUnreadCount',
	'getTournamentMatchdayStats',
	'getTournamentPreview',
	'getTournamentRecap',
	'getTournamentStats',
	'getTrustPolicy',
	'getUpload',
	'getUserPublicHistory',
	'getUserRankedProfile',
	'getUserRankedTrack',
	'getUserStats',
	'getVerifiedEvent',
	'getVerifiedHub',
	'getVerifiedTournamentPreview',
	'hideMyRecap',
	'hideMyTournamentInvite',
	'leaveTournament',
	'listAchievementDefinitions',
	'listCompetitionSeasons',
	'listCreatorCollections',
	'listCreatorEvents',
	'listCreatorTournaments',
	'listCreators',
	'listGameModes',
	'listMatchEvents',
	'listMatchdayMatches',
	'listMatchdays',
	'listMyAchievements',
	'listMyAppeals',
	'listMyBlockedUsers',
	'listMyDevices',
	'listMyFeed',
	'listMyFollowers',
	'listMyFollowing',
	'listMyFriendRequests',
	'listMyFriends',
	'listMyNotifications',
	'listMyPromotions',
	'listMyRankedHistory',
	'listMyRecaps',
	'listMyReports',
	'listMyRewards',
	'listMyTournamentInvites',
	'listMyTrustBlocks',
	'listMyUnlockedAchievements',
	'listMyUpdates',
	'listOauthLinks',
	'listPromotionWinners',
	'listPromotions',
	'listRankedSeasons',
	'listRankedTracks',
	'listRulesets',
	'listSports',
	'listTournamentChatMessages',
	'listTournamentChatMutes',
	'listTournamentChatPins',
	'listTournamentChatUpdates',
	'listTournamentInvitationCodes',
	'listTournamentInvites',
	'listTournamentMembers',
	'listTournamentRecaps',
	'listTrustPolicies',
	'listUserAchievements',
	'listVerifiedEventTournaments',
	'listVerifiedEvents',
	'listVerifiedTournaments',
	'logout',
	'markMyFriendRequestSeen',
	'markMyNotificationRead',
	'markMyNotificationSeen',
	'markMyTournamentInviteSeen',
	'muteTournamentChatUser',
	'optInToPromotion',
	'optOutFromPromotion',
	'pinTournamentChatMessage',
	'refreshSession',
	'registerMyDevice',
	'registerUser',
	'removeFriend',
	'removeTournamentMember',
	'reportTournamentChatContent',
	'requestMyRecap',
	'requestPasswordReset',
	'resendRegistrationConfirmation',
	'resolveInvitationCode',
	'resolveUserByUsername',
	'searchMatches',
	'searchUsers',
	'sendTournamentChatMessage',
	'streamMyLiveUpdates',
	'streamTournamentChatLive',
	'unblockUser',
	'unfollowUser',
	'unmuteTournamentChatUser',
	'unpinTournamentChatMessage',
	'updateMe',
	'updateMyFeedReadCursor',
	'updateMyNotificationPreferences',
	'updateMyPreferences',
	'updateMyPrivacy',
	'updateMyRankedSettings',
	'updateMyRewardFulfillmentProfile',
	'updateTournamentChatReadCursor',
	'updateTournamentChatSettings',
	'updateTournamentMember',
] as const;

type NotImplementedOperationId = (typeof notImplementedOperationIds)[number];

export function createNotImplementedMockHandler(operationId: string): MockHandler<object, NotImplementedProblem> {
	return () => ({
		status: 501,
		response: {
			type: 'https://errors.rankup.dev/mock/not-implemented',
			title: 'Mock Handler Not Implemented',
			status: 501,
			detail: `Mock handler is not implemented for operation ${operationId}.`,
			code: 'mockHandlerNotImplemented',
		},
	});
}

export function createNotImplementedMockHandlers(): Record<NotImplementedOperationId, MockHandler<object, NotImplementedProblem>> {
	const handlers = {} as Record<NotImplementedOperationId, MockHandler<object, NotImplementedProblem>>;
	for (const operationId of notImplementedOperationIds) {
		handlers[operationId] = createNotImplementedMockHandler(operationId);
	}
	return handlers;
}
