export type SharedKeys<TDomain, TApi> = readonly (keyof TDomain & keyof TApi)[];

export const defineSharedKeys =
	<TDomain, TApi>() =>
	<K extends SharedKeys<TDomain, TApi>>(keys: K): K =>
		keys;

export function pickFields<TSource, K extends readonly (keyof TSource)[]>(source: TSource, keys: K): Pick<TSource, K[number]> {
	const result = {} as Pick<TSource, K[number]>;
	for (const key of keys) {
		result[key] = source[key];
	}
	return result;
}

export function mapOptional<TSource, TTarget>(
	value: TSource | null | undefined,
	mapper: (value: TSource) => TTarget,
): TTarget | undefined {
	if (value === null || value === undefined) {
		return undefined;
	}
	return mapper(value);
}

export const gatewayOperationMapping = {
	abortUpload: 'apps/rankup-spa/services/api/media/media-uploads-gateway.ts',
	acceptFriendRequest: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	acceptMyTournamentInvite: 'apps/rankup-spa/services/api/tournaments/tournament-invites-gateway.ts',
	archiveTournament: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	batchUpdateMyNotifications: 'apps/rankup-spa/services/api/engagement/live-gateway.ts',
	blockUser: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	cancelMyFriendRequest: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	cancelTournamentInvite: 'apps/rankup-spa/services/api/tournaments/tournament-invites-gateway.ts',
	changeMyPassword: 'apps/rankup-spa/services/api/accounts/me-gateway.ts',
	claimMyReward: 'apps/rankup-spa/services/api/promotions/promotions-rewards-gateway.ts',
	clearMyMatchdaySubmission: 'apps/rankup-spa/services/api/submissions/tournament-submissions-gateway.ts',
	completeUpload: 'apps/rankup-spa/services/api/media/media-uploads-gateway.ts',
	confirmPasswordReset: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	confirmRegistration: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	createDuel: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	createDuelRematch: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	createFriendRequest: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	createMyAppeal: 'apps/rankup-spa/services/api/trustSafety/trust-appeals-gateway.ts',
	createOauthLink: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	createReport: 'apps/rankup-spa/services/api/trustSafety/trust-reports-gateway.ts',
	createSession: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	createTournament: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	createTournamentInvitationCode: 'apps/rankup-spa/services/api/tournaments/tournament-invitation-codes-gateway.ts',
	createTournamentInvites: 'apps/rankup-spa/services/api/tournaments/tournament-invites-gateway.ts',
	createUpload: 'apps/rankup-spa/services/api/media/media-uploads-gateway.ts',
	declineFriendRequest: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	declineMyTournamentInvite: 'apps/rankup-spa/services/api/tournaments/tournament-invites-gateway.ts',
	deleteMe: 'apps/rankup-spa/services/api/accounts/me-gateway.ts',
	deleteMedia: 'apps/rankup-spa/services/api/media/media-assets-gateway.ts',
	deleteMyDevice: 'apps/rankup-spa/services/api/accounts/me-gateway.ts',
	deleteOauthLink: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	deleteTournament: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	deleteTournamentChatMessage: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	dismissMyNotification: 'apps/rankup-spa/services/api/engagement/live-gateway.ts',
	editTournamentChatMessage: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	followUser: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	getAchievementDefinition: 'apps/rankup-spa/services/api/achievements/achievements-catalog-gateway.ts',
	getAchievementMeta: 'apps/rankup-spa/services/api/achievements/achievements-catalog-gateway.ts',
	getAppBootstrap: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	getAppConfig: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	getCompetition: 'apps/rankup-spa/services/api/sports/sports-catalog-gateway.ts',
	getCompetitionSeason: 'apps/rankup-spa/services/api/sports/sports-catalog-gateway.ts',
	getCreator: 'apps/rankup-spa/services/api/creators/creators-directory-gateway.ts',
	getCreatorCollection: 'apps/rankup-spa/services/api/creators/creators-catalog-gateway.ts',
	getCreatorHub: 'apps/rankup-spa/services/api/creators/creators-catalog-gateway.ts',
	getGameMode: 'apps/rankup-spa/services/api/rules/game-modes-gateway.ts',
	getHealthz: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	getMatch: 'apps/rankup-spa/services/api/sports/sports-schedule-gateway.ts',
	getMatchdayResultsSummary: 'apps/rankup-spa/services/api/scoring/tournament-results-gateway.ts',
	getMe: 'apps/rankup-spa/services/api/accounts/me-gateway.ts',
	getMedia: 'apps/rankup-spa/services/api/media/media-assets-gateway.ts',
	getMyAchievement: 'apps/rankup-spa/services/api/achievements/achievements-grants-gateway.ts',
	getMyAppeal: 'apps/rankup-spa/services/api/trustSafety/trust-appeals-gateway.ts',
	getMyEnforcementStatus: 'apps/rankup-spa/services/api/trustSafety/trust-enforcement-gateway.ts',
	getMyFeedItem: 'apps/rankup-spa/services/api/engagement/live-gateway.ts',
	getMyFeedReadCursor: 'apps/rankup-spa/services/api/engagement/live-gateway.ts',
	getMyFriendRequest: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	getMyFriendRequestUnreadCount: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	getMyMatchdayResults: 'apps/rankup-spa/services/api/scoring/tournament-results-gateway.ts',
	getMyMatchdaySubmission: 'apps/rankup-spa/services/api/submissions/tournament-submissions-gateway.ts',
	getMyNotification: 'apps/rankup-spa/services/api/engagement/live-gateway.ts',
	getMyNotificationPreferences: 'apps/rankup-spa/services/api/accounts/me-gateway.ts',
	getMyNotificationUnreadCount: 'apps/rankup-spa/services/api/engagement/live-gateway.ts',
	getMyPreferences: 'apps/rankup-spa/services/api/accounts/me-gateway.ts',
	getMyPrivacy: 'apps/rankup-spa/services/api/accounts/me-gateway.ts',
	getMyPromotionStatus: 'apps/rankup-spa/services/api/promotions/promotions-campaigns-gateway.ts',
	getMyRankedProfile: 'apps/rankup-spa/services/api/ranked/ranked-leaderboards-gateway.ts',
	getMyRankedSettings: 'apps/rankup-spa/services/api/ranked/ranked-leaderboards-gateway.ts',
	getMyRankedTrack: 'apps/rankup-spa/services/api/ranked/ranked-leaderboards-gateway.ts',
	getMyRecap: 'apps/rankup-spa/services/api/engagement/recaps-gateway.ts',
	getMyRelationshipWithUser: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	getMyReport: 'apps/rankup-spa/services/api/trustSafety/trust-reports-gateway.ts',
	getMyReward: 'apps/rankup-spa/services/api/promotions/promotions-rewards-gateway.ts',
	getMyRewardFulfillmentProfile: 'apps/rankup-spa/services/api/promotions/promotions-rewards-gateway.ts',
	getMyStats: 'apps/rankup-spa/services/api/engagement/stats-gateway.ts',
	getMyTournamentInvite: 'apps/rankup-spa/services/api/tournaments/tournament-invites-gateway.ts',
	getMyTournamentInviteUnreadCount: 'apps/rankup-spa/services/api/tournaments/tournament-invites-gateway.ts',
	getMyTournamentMatchdayRankingWindow: 'apps/rankup-spa/services/api/tournaments/tournament-ranking-gateway.ts',
	getMyTournamentMatchdayStats: 'apps/rankup-spa/services/api/engagement/stats-gateway.ts',
	getMyTournamentSeasonRankingWindow: 'apps/rankup-spa/services/api/tournaments/tournament-ranking-gateway.ts',
	getMyTournamentStats: 'apps/rankup-spa/services/api/engagement/stats-gateway.ts',
	getPromotion: 'apps/rankup-spa/services/api/promotions/promotions-campaigns-gateway.ts',
	getRankedLeaderboard: 'apps/rankup-spa/services/api/ranked/ranked-leaderboards-gateway.ts',
	getRankedMeta: 'apps/rankup-spa/services/api/ranked/ranked-seasons-gateway.ts',
	getRankedSeason: 'apps/rankup-spa/services/api/ranked/ranked-seasons-gateway.ts',
	getRankedSeasonLeaderboard: 'apps/rankup-spa/services/api/ranked/ranked-leaderboards-gateway.ts',
	getRankedTrack: 'apps/rankup-spa/services/api/ranked/ranked-seasons-gateway.ts',
	getReadyz: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	getRuleset: 'apps/rankup-spa/services/api/rules/rulesets-gateway.ts',
	getTeam: 'apps/rankup-spa/services/api/sports/sports-catalog-gateway.ts',
	getTournament: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	getTournamentChat: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	getTournamentChatMessage: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	getTournamentChatReadCursor: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	getTournamentChatUnreadCount: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	getTournamentMatchday: 'apps/rankup-spa/services/api/tournaments/tournament-matchdays-gateway.ts',
	getTournamentMatchdayAvailability: 'apps/rankup-spa/services/api/tournaments/tournament-matchdays-gateway.ts',
	getTournamentMatchdayStats: 'apps/rankup-spa/services/api/engagement/stats-gateway.ts',
	getTournamentPreview: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	getTournamentRecap: 'apps/rankup-spa/services/api/engagement/recaps-gateway.ts',
	getTournamentRules: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	getTournamentStats: 'apps/rankup-spa/services/api/engagement/stats-gateway.ts',
	getTrustPolicy: 'apps/rankup-spa/services/api/trustSafety/trust-policies-gateway.ts',
	getUpload: 'apps/rankup-spa/services/api/media/media-uploads-gateway.ts',
	getUserMatchdayResults: 'apps/rankup-spa/services/api/scoring/tournament-results-gateway.ts',
	getUserMatchdaySubmission: 'apps/rankup-spa/services/api/submissions/tournament-submissions-gateway.ts',
	getUserPublicHistory: 'apps/rankup-spa/services/api/accounts/users-gateway.ts',
	getUserPublicProfile: 'apps/rankup-spa/services/api/accounts/users-gateway.ts',
	getUserRankedProfile: 'apps/rankup-spa/services/api/ranked/ranked-leaderboards-gateway.ts',
	getUserRankedTrack: 'apps/rankup-spa/services/api/ranked/ranked-leaderboards-gateway.ts',
	getUserStats: 'apps/rankup-spa/services/api/engagement/stats-gateway.ts',
	getVerifiedEvent: 'apps/rankup-spa/services/api/verified/verified-events-gateway.ts',
	getVerifiedHub: 'apps/rankup-spa/services/api/verified/verified-hub-gateway.ts',
	getVerifiedTournamentPreview: 'apps/rankup-spa/services/api/verified/verified-events-gateway.ts',
	hideMyRecap: 'apps/rankup-spa/services/api/engagement/recaps-gateway.ts',
	hideMyTournamentInvite: 'apps/rankup-spa/services/api/tournaments/tournament-invites-gateway.ts',
	joinTournament: 'apps/rankup-spa/services/api/tournaments/tournament-members-gateway.ts',
	joinTournamentByInvitationCode: 'apps/rankup-spa/services/api/tournaments/tournament-invitation-codes-gateway.ts',
	leaveTournament: 'apps/rankup-spa/services/api/tournaments/tournament-members-gateway.ts',
	listAchievementDefinitions: 'apps/rankup-spa/services/api/achievements/achievements-catalog-gateway.ts',
	listCompetitionSeasons: 'apps/rankup-spa/services/api/sports/sports-catalog-gateway.ts',
	listCompetitions: 'apps/rankup-spa/services/api/sports/sports-catalog-gateway.ts',
	listCreatorCollections: 'apps/rankup-spa/services/api/creators/creators-catalog-gateway.ts',
	listCreatorEvents: 'apps/rankup-spa/services/api/creators/creators-catalog-gateway.ts',
	listCreatorTournaments: 'apps/rankup-spa/services/api/creators/creators-catalog-gateway.ts',
	listCreators: 'apps/rankup-spa/services/api/creators/creators-directory-gateway.ts',
	listDiscoverableTournaments: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	listGameModes: 'apps/rankup-spa/services/api/rules/game-modes-gateway.ts',
	listMatchEvents: 'apps/rankup-spa/services/api/sports/sports-schedule-gateway.ts',
	listMatchdayMatches: 'apps/rankup-spa/services/api/sports/sports-schedule-gateway.ts',
	listMatchdaySubmissions: 'apps/rankup-spa/services/api/submissions/tournament-submissions-gateway.ts',
	listMatchdays: 'apps/rankup-spa/services/api/sports/sports-schedule-gateway.ts',
	listMyAchievements: 'apps/rankup-spa/services/api/achievements/achievements-grants-gateway.ts',
	listMyAppeals: 'apps/rankup-spa/services/api/trustSafety/trust-appeals-gateway.ts',
	listMyBlockedUsers: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	listMyDevices: 'apps/rankup-spa/services/api/accounts/me-gateway.ts',
	listMyDuels: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	listMyFeed: 'apps/rankup-spa/services/api/engagement/live-gateway.ts',
	listMyFollowers: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	listMyFollowing: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	listMyFriendRequests: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	listMyFriends: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	listMyNotifications: 'apps/rankup-spa/services/api/engagement/live-gateway.ts',
	listMyPromotions: 'apps/rankup-spa/services/api/promotions/promotions-campaigns-gateway.ts',
	listMyRankedHistory: 'apps/rankup-spa/services/api/ranked/ranked-leaderboards-gateway.ts',
	listMyRecaps: 'apps/rankup-spa/services/api/engagement/recaps-gateway.ts',
	listMyReports: 'apps/rankup-spa/services/api/trustSafety/trust-reports-gateway.ts',
	listMyRewards: 'apps/rankup-spa/services/api/promotions/promotions-rewards-gateway.ts',
	listMyTournamentInvites: 'apps/rankup-spa/services/api/tournaments/tournament-invites-gateway.ts',
	listMyTournaments: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	listMyTrustBlocks: 'apps/rankup-spa/services/api/trustSafety/trust-reports-gateway.ts',
	listMyUnlockedAchievements: 'apps/rankup-spa/services/api/achievements/achievements-grants-gateway.ts',
	listMyUpdates: 'apps/rankup-spa/services/api/engagement/updates-gateway.ts',
	listOauthLinks: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	listPromotionWinners: 'apps/rankup-spa/services/api/promotions/promotions-campaigns-gateway.ts',
	listPromotions: 'apps/rankup-spa/services/api/promotions/promotions-campaigns-gateway.ts',
	listRankedSeasons: 'apps/rankup-spa/services/api/ranked/ranked-seasons-gateway.ts',
	listRankedTracks: 'apps/rankup-spa/services/api/ranked/ranked-seasons-gateway.ts',
	listRulesets: 'apps/rankup-spa/services/api/rules/rulesets-gateway.ts',
	listSports: 'apps/rankup-spa/services/api/sports/sports-catalog-gateway.ts',
	listTournamentChatMessages: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	listTournamentChatMutes: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	listTournamentChatPins: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	listTournamentChatUpdates: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	listTournamentInvitationCodes: 'apps/rankup-spa/services/api/tournaments/tournament-invitation-codes-gateway.ts',
	listTournamentInvites: 'apps/rankup-spa/services/api/tournaments/tournament-invites-gateway.ts',
	listTournamentMatchdayMatches: 'apps/rankup-spa/services/api/tournaments/tournament-matchdays-gateway.ts',
	listTournamentMatchdayRanking: 'apps/rankup-spa/services/api/tournaments/tournament-ranking-gateway.ts',
	listTournamentMatchdays: 'apps/rankup-spa/services/api/tournaments/tournament-matchdays-gateway.ts',
	listTournamentMembers: 'apps/rankup-spa/services/api/tournaments/tournament-members-gateway.ts',
	listTournamentRecaps: 'apps/rankup-spa/services/api/engagement/recaps-gateway.ts',
	listTournamentSeasonRanking: 'apps/rankup-spa/services/api/tournaments/tournament-ranking-gateway.ts',
	listTournamentUpdates: 'apps/rankup-spa/services/api/engagement/updates-gateway.ts',
	listTrustPolicies: 'apps/rankup-spa/services/api/trustSafety/trust-policies-gateway.ts',
	listUserAchievements: 'apps/rankup-spa/services/api/achievements/achievements-grants-gateway.ts',
	listVerifiedEventTournaments: 'apps/rankup-spa/services/api/verified/verified-events-gateway.ts',
	listVerifiedEvents: 'apps/rankup-spa/services/api/verified/verified-events-gateway.ts',
	listVerifiedTournaments: 'apps/rankup-spa/services/api/verified/verified-events-gateway.ts',
	lockTournament: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	logout: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	markMyFriendRequestSeen: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	markMyNotificationRead: 'apps/rankup-spa/services/api/engagement/live-gateway.ts',
	markMyNotificationSeen: 'apps/rankup-spa/services/api/engagement/live-gateway.ts',
	markMyTournamentInviteSeen: 'apps/rankup-spa/services/api/tournaments/tournament-invites-gateway.ts',
	muteTournamentChatUser: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	oauthAuthorize: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	oauthTokenExchange: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	optInToPromotion: 'apps/rankup-spa/services/api/promotions/promotions-campaigns-gateway.ts',
	optOutFromPromotion: 'apps/rankup-spa/services/api/promotions/promotions-campaigns-gateway.ts',
	pinTournamentChatMessage: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	refreshSession: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	registerMyDevice: 'apps/rankup-spa/services/api/accounts/me-gateway.ts',
	registerUser: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	removeFriend: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	removeTournamentMember: 'apps/rankup-spa/services/api/tournaments/tournament-members-gateway.ts',
	reportTournamentChatContent: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	requestMyRecap: 'apps/rankup-spa/services/api/engagement/recaps-gateway.ts',
	requestPasswordReset: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	resendRegistrationConfirmation: 'apps/rankup-spa/services/api/accounts/auth-gateway.ts',
	resolveInvitationCode: 'apps/rankup-spa/services/api/tournaments/tournament-invitation-codes-gateway.ts',
	resolveUserByUsername: 'apps/rankup-spa/services/api/accounts/users-gateway.ts',
	searchMatches: 'apps/rankup-spa/services/api/sports/sports-schedule-gateway.ts',
	searchUsers: 'apps/rankup-spa/services/api/accounts/users-gateway.ts',
	sendTournamentChatMessage: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	streamMyLiveUpdates: 'apps/rankup-spa/services/api/engagement/updates-gateway.ts',
	streamTournamentChatLive: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	streamTournamentLive: 'apps/rankup-spa/services/api/engagement/live-gateway.ts',
	transferTournamentOwnership: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	unarchiveTournament: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	unblockUser: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	unfollowUser: 'apps/rankup-spa/services/api/accounts/social-gateway.ts',
	unlockTournament: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	unmuteTournamentChatUser: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	unpinTournamentChatMessage: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	updateMe: 'apps/rankup-spa/services/api/accounts/me-gateway.ts',
	updateMyFeedReadCursor: 'apps/rankup-spa/services/api/engagement/live-gateway.ts',
	updateMyNotificationPreferences: 'apps/rankup-spa/services/api/accounts/me-gateway.ts',
	updateMyPreferences: 'apps/rankup-spa/services/api/accounts/me-gateway.ts',
	updateMyPrivacy: 'apps/rankup-spa/services/api/accounts/me-gateway.ts',
	updateMyRankedSettings: 'apps/rankup-spa/services/api/ranked/ranked-leaderboards-gateway.ts',
	updateMyRewardFulfillmentProfile: 'apps/rankup-spa/services/api/promotions/promotions-rewards-gateway.ts',
	updateTournament: 'apps/rankup-spa/services/api/tournaments/tournament-core-gateway.ts',
	updateTournamentChatReadCursor: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	updateTournamentChatSettings: 'apps/rankup-spa/services/api/engagement/tournament-chat-gateway.ts',
	updateTournamentMember: 'apps/rankup-spa/services/api/tournaments/tournament-members-gateway.ts',
	upsertMyMatchdaySubmission: 'apps/rankup-spa/services/api/submissions/tournament-submissions-gateway.ts',
} as const;

export type GatewayOperationId = keyof typeof gatewayOperationMapping;
export type GatewayOperationOwner = (typeof gatewayOperationMapping)[GatewayOperationId];
